(setq require-final-newline t)
(setq auto-mode-alist (cons '("\\.tt$" . html-mode) auto-mode-alist))
(setq-default show-trailing-whitespace t)

(defun iwb ()
  "indent whole buffer"
  (interactive)
  (delete-trailing-whitespace)
  (indent-region (point-min) (point-max) nil)
  (untabify (point-min) (point-max)))
(global-set-key [f12] 'iwb)
(global-set-key [f10] 'show-trailing-whitespace)
(global-set-key [f11] 'delete-trailing-whitespace)
(add-to-list 'load-path "~/.emacs.d/")
(load "js2.el")
(load "js2.elc")
(autoload 'js2-mode "js2" nil t)
(add-to-list 'auto-mode-alist '("\\.js$" . js2-mode))
(add-to-list 'auto-mode-alist '("\\.json$" . js2-mode))
(load "json-mode.el")
